name: 🐞 Bug report
description: Something in kotlinx.coroutines behaves incorrectly
title: "[Bug] "
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        Thanks for the report!

        Please focus on **what happens** and **how to reproduce it**.
        Everything else is optional.

        If you’re not sure whether this is a bug or just unclear behavior,
        you might get a quicker answer on
        [StackOverflow](https://stackoverflow.com/) or in the
        [Kotlin Slack](https://slack-chats.kotlinlang.org/).

  - type: textarea
    id: problem
    attributes:
      label: What is happening?
      placeholder: |
        Describe what looks wrong or unexpected.
    validations:
      required: true

  - type: textarea
    id: reproducer
    attributes:
      label: Reproducer
      description: |
        A minimal, self-contained example is the most helpful thing you can provide.
      placeholder: |
        ```kotlin
        runBlocking {
            // minimal example
        }
        ```
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Anything else? (optional)
      placeholder: |
        What you expected, versions, environment, logs, links — whatever you think matters.
    validations:
      required: false
