name: ✨ Feature Request
description: Suggest a new feature or enhancement for kotlinx.coroutines
title: "[FEATURE] "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for suggesting a feature!

        We love hearing ideas from our community. Please help us understand your use case by filling out the sections below.
        Before submitting, please check if this feature has already been requested.

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      options:
        - label: I have searched [existing requests](https://github.com/Kotlin/kotlinx.coroutines/issues?q=is%3Aissue+label%3Aenhancement) and this feature hasn't been requested yet
          required: true
        - label: I have checked the latest version of the library to see if it's already implemented
          required: true
        - label: I have considered if this feature is better suited for a third-party library
          required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: |
        Explain what *specifically* you are trying to do and why.
        Focus on the problem, not the solution.
      placeholder: |
        Example: "I have a `SharedFlow<Double>` that represents readings from an external device..."
    validations:
      required: true

  - type: textarea
    id: api_shape
    attributes:
      label: The Shape of the API
      description: |
        What could the desired API look like? What would some sample code using the new feature look like?
        If you don't have a clear idea, pseudocode or just explaining the API shape is also perfectly fine.
      placeholder: |
        ```kotlin
        fun <T> Flow<T>.myNewOperator(): Flow<T> = ...
        ```
    validations:
      required: true

  - type: textarea
    id: prior_art
    attributes:
      label: Prior Art
      description: |
        Are there any existing solutions, or does another library (like RxJava) have a similar feature?
      placeholder: |
        RxJava has feature X, which solves this by...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your workflow?
      options:
        - Critical - Blocking my work
        - High - Significant impact on productivity
        - Medium - Would be very helpful
        - Low - Nice to have
      default: 2
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        - Screenshots or mockups
        - Links to similar features
        - Technical considerations
      placeholder: Add any other context here...
    validations:
      required: false
