name: 🎨 Design Considerations
description: Suggest changes to suboptimal but intentional library behavior
title: "[DESIGN] "
labels:
  - design
body:
  - type: markdown
    attributes:
      value: |
        ## Design Considerations

        This is a place for issue reports that are not exactly bugs (wrong unintentional behavior) but for our library behaving suboptimally (though this could have been intentional).

        **Before filing**, consider:
        - If the behavior is strange, surprising, and undocumented, it could be a good idea to file a **Bug report** instead.
        - Is this still relevant with the latest version of the library? We could have changed this already.
        - Maybe there are good reasons for the existing behavior. Please try searching for existing discussions of the problem.
        - Are you using the right abstraction? Consider asking on [StackOverflow](https://stackoverflow.com/) or the [Kotlin Slack](https://surveys.jetbrains.com/s3/kotlin-slack-sign-up).

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      options:
        - label: I have searched existing discussions and this issue hasn't been raised yet
          required: true
        - label: I have checked the latest version of the library to see if the behavior is still the same
          required: true
        - label: I have considered if my need is better solved by some other abstraction
          required: true

  - type: textarea
    id: current_behavior
    attributes:
      label: What do we have now?
      description: Preferably with specific code examples.
      placeholder: |
        Currently, the API behaves like this...
        ```kotlin
        // Code example
        ```
    validations:
      required: true

  - type: textarea
    id: proposed_behavior
    attributes:
      label: What should be instead?
      description: Preferably with specific code examples.
      placeholder: |
        It would be better if...
        ```kotlin
        // Code example
        ```
    validations:
      required: true

  - type: textarea
    id: pros
    attributes:
      label: Why?
      description: |
        The upsides of your proposal.
        - Who would benefit from this and how?
        - Would it be possible to cover new use cases?
        - Would some code become clearer?
        - Would the library become conceptually simpler?
      placeholder: |
        This change would allow...
    validations:
      required: true

  - type: textarea
    id: cons
    attributes:
      label: Why not?
      description: |
        The downsides of your proposal that you already see.
        - Is this a breaking change?
        - Are there use cases that are better solved by what we have now?
        - Does some code become less clear after this change?
      placeholder: |
        One downside could be...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this change to your workflow?
      options:
        - Critical - Blocking my work
        - High - Significant impact on productivity
        - Medium - Would be very helpful
        - Low - Nice to have
      default: 2
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Anything else that may help understand the proposal.
      placeholder: Add any other context here...
    validations:
      required: false
